CREATE TABLE IF NOT EXISTS pga_value (
    id BIGSERIAL PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    dd1 DOUBLE PRECISION NOT NULL,
    dd2 DOUBLE PRECISION NOT NULL,
    dd3 DOUBLE PRECISION NOT NULL,
    dd4 DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pga_lat_long
    ON pga_value (latitude, longitude);
